### ISSUE TITLE
How to use the Docker Image?

### ISSUE THREAD

**Issue by PythonLinks** [iodide-project/iodide#1657]
###Short summary of the bug.

There is a docker container for iodide.
https://hub.docker.com/r/mozilla/iodide/tags

But no instructions on how to start it. 

So I tried copying and modifying the pyodide/run_docker script.

 #Please include the IODIDE version number where you found the bug 

MASTER

### What I Did
Tried to get the iodide dockerfile running.  

### code sample or exact steps that causes the bug

DOCKER_PORT=8000
SYSTEM_PORT=8084

docker run -p $SYSTEM_PORT:$DOCKER_PORT  -v $PWD:/app --user root -e "SECRET_KEY=MYSECRETKEY" -e NB_UID=$UID -e NB_GID=$GID -it mozilla/iodide:latest 

### What I Expected
I expected to find clear documentation. Instead I had to poke around. Til I got stuck. 

### What Happened 

 I get stuck on the error message below.

________________

 ./run_docker
Waiting for db to listen on 5432...
nc: bad address 'db'
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 82, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/loader.py", line 212, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 61, in applied_migrations
    if self.has_table():
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 44, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 255, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/dummy/base.py", line 20, in complain
    raise ImproperlyConfigured("settings.DATABASES is improperly configured. "
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.

Thank You
Chris

**Comment by wlach** [comment]
Hi, the docker image on dockerhub is intended more for a specific deployment context inside Mozilla, and is not something we can really support. If you just want to experiment with an iodide server, I'd recommend starting with our local deployment instructions here:

https://iodide-project.github.io/docs/local-dev/
