### ISSUE TITLE
test_post_to_file_api is not stable

### ISSUE THREAD

**Issue by zzl0** [iodide-project/iodide#2497]
`test_post_to_file_api` test will fail when run it the second time.

### What I Did

```bash
$ make shell
$ cd server/tests/
$ pytest test_file_api.py::test_post_to_file_api  # succeeded
$ pytest test_file_api.py::test_post_to_file_api  # failed
```
### What I Expected

I expect the test always succeed.

### What Happened 

```
Traceback (most recent call last):
  File "/app/server/tests/test_file_api.py", line 32, in test_post_to_file_api
    created_file = File.objects.get(id=1)
  File "/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/venv/lib/python3.8/site-packages/django/db/models/query.py", line 406, in get
    raise self.model.DoesNotExist(
server.files.models.File.DoesNotExist: File matching query does not exist.
```

**Comment by wlach** [comment]
Yeah, we shouldn't be relying on ids having specific values in tests.
