### ISSUE TITLE
Race condition while spinning up containers for local development

### ISSUE THREAD

**Issue by nrgoncalves** [iodide-project/iodide#2933]
It seems that there is a race condition while composing the containers for local development, whereby the migrations script is sometimes being executed before the database is ready to accept any connections. 

### What I Did

Followed the instructions detailed here: https://iodide-project.github.io/docs/local-dev/

### What Happened 

Running `make up` eventually produces the following: 

```
server_1  | Traceback (most recent call last):
server_1  |   File "/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
server_1  |     self.connect()
server_1  |   File "/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
server_1  |     return func(*args, **kwargs)
server_1  |   File "/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 197, in connect
server_1  |     self.connection = self.get_new_connection(conn_params)
server_1  |   File "/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
server_1  |     return func(*args, **kwargs)
server_1  |   File "/venv/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 185, in get_new_connection
server_1  |     connection = Database.connect(**conn_params)
server_1  |   File "/venv/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
server_1  |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
server_1  | psycopg2.OperationalError: could not connect to server: Connection refused
server_1  | 	Is the server running on host "db" (172.22.0.3) and accepting
server_1  | 	TCP/IP connections on port 5432?
server_1  | 
server_1  | 
server_1  | The above exception was the direct cause of the following exception:
server_1  | 
server_1  | Traceback (most recent call last):
server_1  |   File "manage.py", line 10, in <module>
server_1  |     execute_from_command_line(sys.argv)
server_1  |   File "/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
server_1  |     utility.execute()
server_1  |   File "/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
server_1  |     self.fetch_command(subcommand).run_from_argv(self.argv)
server_1  |   File "/venv/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
server_1  |     self.execute(*args, **cmd_options)
server_1  |   File "/venv/lib/python3.8/site-packages/django/core/management/base.py", line 369, in execute
server_1  |     output = self.handle(*args, **options)
server_1  |   File "/venv/lib/python3.8/site-packages/django/core/management/base.py", line 83, in wrapped
server_1  |     res = handle_func(*args, **kwargs)
server_1  |   File "/venv/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 86, in handle
server_1  |     executor = MigrationExecutor(connection, self.migration_progress_callback)
server_1  |   File "/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 18, in __init__
server_1  |     self.loader = MigrationLoader(self.connection)
server_1  |   File "/venv/lib/python3.8/site-packages/django/db/migrations/loader.py", line 49, in __init__
server_1  |     self.build_graph()
server_1  |   File "/venv/lib/python3.8/site-packages/django/db/migrations/loader.py", line 212, in build_graph
server_1  |     self.applied_migrations = recorder.applied_migrations()
server_1  |   File "/venv/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 76, in applied_migrations
server_1  |     if self.has_table():
server_1  |   File "/venv/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 56, in has_table
server_1  |     return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
server_1  |   File "/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
server_1  |     return func(*args, **kwargs)
server_1  |   File "/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 260, in cursor
server_1  |     return self._cursor()
server_1  |   File "/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 236, in _cursor
server_1  |     self.ensure_connection()
server_1  |   File "/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
server_1  |     return func(*args, **kwargs)
server_1  |   File "/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
server_1  |     self.connect()
server_1  |   File "/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
server_1  |     raise dj_exc_value.with_traceback(traceback) from exc_value
server_1  |   File "/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
server_1  |     self.connect()
server_1  |   File "/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
server_1  |     return func(*args, **kwargs)
server_1  |   File "/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 197, in connect
server_1  |     self.connection = self.get_new_connection(conn_params)
server_1  |   File "/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
server_1  |     return func(*args, **kwargs)
server_1  |   File "/venv/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 185, in get_new_connection
server_1  |     connection = Database.connect(**conn_params)
server_1  |   File "/venv/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
server_1  |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
server_1  | django.db.utils.OperationalError: could not connect to server: Connection refused
server_1  | 	Is the server running on host "db" (172.22.0.3) and accepting
server_1  | 	TCP/IP connections on port 5432?
db_1      |  done
db_1      | server started
db_1      | 
db_1      | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
db_1      | 
db_1      | waiting for server to shut down....LOG:  received fast shutdown request
db_1      | LOG:  aborting any active transactions
db_1      | LOG:  autovacuum launcher shutting down
db_1      | LOG:  shutting down
db_1      | LOG:  database system is shut down
iodide_server_1 exited with code 1
db_1      |  done
db_1      | server stopped
db_1      | 
db_1      | PostgreSQL init process complete; ready for start up.
db_1      | 
db_1      | LOG:  database system was shut down at 2020-08-02 20:59:37 UTC
db_1      | LOG:  MultiXact member wraparound protections are now enabled
db_1      | LOG:  autovacuum launcher started
db_1      | LOG:  database system is ready to accept connections

```

A quick and dirty change to `bin/run` seems to avoid the issue, indicating that this is indeed a race condition:

```sh
case $1 in
  dev)
    sleep 60
    python manage.py migrate --noinput
    exec python manage.py runserver 0.0.0.0:${PORT}
    ;;
```

In https://github.com/iodide-project/iodide/issues/716#issuecomment-668058215, @wlach pointed out that a workaround is in place to avoid the same thing from happening in CI builds. That same workaround could potentially be used in `bin/run` as well

This is very minor but I am happy to help if you're accepting contributions.

**Comment by wlach** [comment]
@nrgoncalves feel free to make a PR! please tag me on it so I see it
