### ISSUE TITLE
cell-reducer.js:163 Uncaught TypeError: Failed to construct 'DOMException': Please use the 'new' operator, this DOM object constructor cannot be called as a function.

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#451]
This is a Chrome-specific bug, found while trying a new example notebook out. I cannot reproduce this on FF.

This appears to be a problem in `validatedReducer`, called while running:

```javascript
var URL = 'complete.csv'
var data = d3.csvParse(getData(URL))
data.slice(0,10)
```

Which should be a dataset represented as an array of objects. @bcolloran any ideas here? Not fully familiar with `validatedReducer` at this point.

The whole enchilada:

```
Uncaught TypeError: Failed to construct 'DOMException': Please use the 'new' operator, this DOM object constructor cannot be called as a function.
    at cellReducer (https://iodide-project.github.io/master/iodide.master.js:73486:27)
    at reducers.reduce (https://iodide-project.github.io/master/iodide.master.js:73123:59)
    at Array.reduce (<anonymous>)
    at https://iodide-project.github.io/master/iodide.master.js:73123:42
    at validatedReducer (https://iodide-project.github.io/master/iodide.master.js:68082:25)
    at dispatch (https://iodide-project.github.io/master/iodide.master.js:45899:22)
    at Object.dispatch (https://iodide-project.github.io/master/iodide.master.js:68053:7806)
    at Object.dispatcher.(anonymous function).params [as evaluateCell] (https://iodide-project.github.io/master/iodide.master.js:12209:95)
    at UserTask.callback (https://iodide-project.github.io/master/iodide.master.js:12267:16)
    at args.keybindingCallback.e (https://iodide-project.github.io/master/iodide.master.js:17387:17)
```

**Comment by bcolloran** [comment]
@hamilton hard to say for sure from that trace, but it looks like validatedReducer calls the normal reducer without issue, and that the crash is happening within cellReducer.

It'll be trivial to check if the problem is in the validatedReducer-- in store.js, just comment out the createValidatedReducer line and uncomment the regular reducer line:

```
const store = createStore(
  createValidatedReducer(reducer, stateSchema),
  // reducer,
  initializeNotebook(),
  compose(applyMiddleware(createLogger({
    predicate: (getState, action) => action.type !== 'UPDATE_INPUT_CONTENT',
  }))),
)
```

to:

```
const store = createStore(
  // createValidatedReducer(reducer, stateSchema),
  reducer,
  initializeNotebook(),
  compose(applyMiddleware(createLogger({
    predicate: (getState, action) => action.type !== 'UPDATE_INPUT_CONTENT',
  }))),
)
```

**Comment by hamilton** [comment]
This is a pretty serious bug, since we cannot run any of the example notebooks in Chrome.
